version: '3.1'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: lineschool
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 9000:8080
